profiles:
  cam0:
    description: Left camera (CSI port 0)
    resolution:
    - 4608
    - 2592
    rotation: 270
    hflip: true
    vflip: false
    crop:
    - 2048
    - 2048
    offset_x: 0
    offset_y: 0
    awb_enable: true
    awb_mode: indoor
    colour_gains:
    - 1.0
    - 1.0
  cam1:
    description: Right camera (CSI port 1)
    resolution:
    - 4608
    - 2592
    rotation: 90
    hflip: false
    vflip: false
    crop:
    - 2048
    - 2048
    offset_x: 0
    offset_y: 0
    awb_enable: true
    awb_mode: indoor
    colour_gains:
    - 1.0
    - 1.0
calibration:
  chessboard:
    columns: 9
    rows: 6
    square_size_m: 0.024
  output_dir: data/calibration
  notes: 'Capture at least 30 well-lit views per camera covering the full FOV.

    Use `scripts/capture_calibration.py` with matching board settings above.

    '
